# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: '3'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.12
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./docker-compose-config.xml:/etc/clickhouse-server/conf.d/config.xml
      - ./docker-compose-user-config.xml:/etc/clickhouse-server/users.d/users.xml
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '8900:9000'
      - '8901:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=test
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc cp /data/addresses.csv myminio/test/addresses.csv;
      exit 0;"
    volumes:
      - ./addresses.csv:/data/addresses.csv